// First, and deliberately: it records when the app started, and an import that follows it is an
// import it measures.
import './started.ts';
import { AppRegistry, Image, Platform, processColor } from 'react-native';
import { mountNative } from '@solid-native/platform/solid';
import { getFabricUIManager, registerPlatformComponents } from '@solid-native/fabric';
import {
  registerExpoUiViews,
  registerExpoView,
  registerExpoViews,
  registerExpoMap,
} from '@solid-native/expo/views';
import { mountCanary } from './bootstrap.solid.tsx';
// The Tailwind screen's utilities, generated by the Metro config: see src/tailwind.css.
import tailwind from '../.solid-native/app.tailwind.js';

/**
 * The canary's entry, rendered by Solid. The `.solid.ts` suffix is what gives this file Metro's
 * clean native reload in development: an edit here disposes every root and reloads the JS VM.
 */

// registerRunnable, not registerComponent: RN stores a raw mount callback and never
// renders it with its own renderer. This is the seam the whole project hangs off.
registerPlatformComponents(Platform.OS);

// expo-image's Fabric view, under an element name of our choosing. Its React component is
// skipped entirely; the props the component would have computed are written in the template.
registerExpoView('expo-image', 'ExpoImage');
// Liquid Glass, SF Symbols and the Sign in with Apple button, for their typed components.
registerExpoViews('expo-glass', 'expo-glass-container', 'expo-symbol', 'apple-sign-in-button');
// The SwiftUI and Compose controls, by name.
registerExpoUiViews(Platform.OS as 'ios' | 'android');
// `<expo-map>`: expo-maps' Apple view here, its Google view on Android.
registerExpoMap(Platform.OS as 'ios' | 'android');

const engineOptions = {
  processColor,
  // require()d images compile to an asset id; only this turns one into a usable source.
  resolveAssetSource: (value: unknown) => Image.resolveAssetSource(value as never),
};

/**
 * The benchmark builds: the same screen, one renderer each, chosen at build time.
 *
 *     EXPO_PUBLIC_BENCH=solid pnpm --filter canary release:ios   (once, to install a bench app)
 *     examples/canary/src/bench/run.sh solid 5
 *     examples/canary/src/bench/run.sh react 5
 *     examples/canary/src/bench/run.sh signals 5   (Solid with signals and createSelector)
 *
 * `require` rather than `import` so neither screen reaches an ordinary bundle, and a literal path
 * because Metro builds its graph from those.
 */
declare global {
  namespace NodeJS {
    // Declared so Expo can inline it: it rewrites only the dotted `process.env.EXPO_PUBLIC_*`.
    interface ProcessEnv {
      EXPO_PUBLIC_BENCH?: 'solid' | 'signals' | 'react';
    }
  }
}
const bench: string | undefined = process.env.EXPO_PUBLIC_BENCH;
if (bench) {
  // The instrument is a Metro polyfill, so the wrapper has been on the global since before React
  // Native's core loaded the Fabric renderer and took its copy of the methods - which is the only
  // moment React can be measured. Now that it has, the real host object goes back: native casts
  // whatever is there straight to C++, and a plain object would be a segfault, not an error.
  // React Native loads that renderer lazily, so load it here: copied after the restore, React
  // would hold the real host and never be measured.
  require('react-native/Libraries/Renderer/shims/ReactFabric');
  (require('./bench/fabric-instrument.ts') as { restoreFabric(): void }).restoreFabric();
}
if (bench === 'react') {
  const { ReactBench } = require('./bench/react-bench.ts') as { ReactBench: () => unknown };
  AppRegistry.registerComponent('main', () => ReactBench as never);
} else if (bench === 'solid' || bench === 'signals') {
  const { SolidBench } = require('./bench/solid-bench.solid.tsx') as {
    SolidBench: () => never;
  };
  const { SignalsBench } = require('./bench/signals-bench.solid.tsx') as {
    SignalsBench: () => never;
  };
  AppRegistry.registerRunnable('main', ({ rootTag }) => {
    const { wrappedFabric } = require('./bench/fabric-instrument.ts') as {
      wrappedFabric(): never;
    };
    // Handed the wrapper directly, where React's renderer had to be caught reading the global.
    mountNative(bench === 'solid' ? SolidBench : SignalsBench, {
      fabric: wrappedFabric(),
      rootTag: Number(rootTag),
      engineOptions,
    });
  });
} else if (bench) {
  throw new Error(
    `EXPO_PUBLIC_BENCH=${bench}: the benchmark renderers are solid, signals and react.`,
  );
} else {
  // Initial conditions, density tokens and the live condition watcher all belong to this root.
  AppRegistry.registerRunnable('main', ({ rootTag }) => {
    mountCanary({
      fabric: getFabricUIManager(),
      rootTag: Number(rootTag),
      tailwind,
      engineOptions,
    });
  });
}
